export const SEED_TOPICS = [
  // Biology (7 topics)
  {
    title: 'Photosynthesis',
    domain: 'science',
    description: 'How plants make their own food using sunlight, water, and carbon dioxide.',
    key_concepts: ['Plants use sunlight as energy', 'Carbon dioxide and water are ingredients', 'Oxygen is released as a byproduct', 'Chlorophyll makes leaves green'],
    common_misconceptions: ['Plants get food from the soil', 'Plants only need water to grow', 'Photosynthesis only happens during the day'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },
  {
    title: 'Animal Adaptations',
    domain: 'science',
    description: 'How animals develop special features to survive in their environments.',
    key_concepts: ['Camouflage helps animals hide', 'Thick fur keeps animals warm', 'Long necks help giraffes reach food', 'Adaptations happen over many generations'],
    common_misconceptions: ['Animals choose to adapt', 'Adaptations happen in one lifetime', 'All animals can adapt to any environment'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 11,
  },
  {
    title: 'The Human Heart',
    domain: 'science',
    description: 'How the heart pumps blood through your body to deliver oxygen and nutrients.',
    key_concepts: ['The heart has four chambers', 'Blood carries oxygen to cells', 'Arteries carry blood away from the heart', 'Veins carry blood back to the heart'],
    common_misconceptions: ['The heart is on the left side of the chest', 'Blood is blue when it has no oxygen', 'Your heart stops when you sneeze'],
    difficulty_level: 2,
    age_range_min: 8,
    age_range_max: 12,
  },
  {
    title: 'Food Chains',
    domain: 'science',
    description: 'How energy passes from one living thing to another through eating.',
    key_concepts: ['Producers make their own food', 'Consumers eat other organisms', 'Decomposers break down dead things', 'Energy flows from sun to producers to consumers'],
    common_misconceptions: ['Animals at the top of the food chain are the strongest', 'Removing one animal doesn\'t affect others', 'Food chains are always simple and linear'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 10,
  },
  {
    title: 'How Lungs Work',
    domain: 'science',
    description: 'How your lungs help you breathe in oxygen and breathe out carbon dioxide.',
    key_concepts: ['Lungs expand when you breathe in', 'Oxygen passes into the blood', 'Carbon dioxide is waste from cells', 'The diaphragm muscle controls breathing'],
    common_misconceptions: ['We breathe in pure oxygen', 'Lungs push air out by squeezing', 'We only use a small part of our lungs'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },
  {
    title: 'Plant Life Cycle',
    domain: 'science',
    description: 'How plants grow from seeds, make flowers, and create new seeds.',
    key_concepts: ['Seeds need water, warmth, and soil to germinate', 'Roots grow down, stems grow up', 'Flowers help plants reproduce', 'Seeds spread through wind, water, and animals'],
    common_misconceptions: ['All plants grow from seeds', 'Plants only grow in spring', 'All seeds need to be buried deep in soil'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 10,
  },
  {
    title: 'Habitats and Ecosystems',
    domain: 'science',
    description: 'How living things depend on their environment and each other to survive.',
    key_concepts: ['A habitat provides food, water, and shelter', 'Different animals live in different habitats', 'Living and non-living things interact in ecosystems', 'Changing a habitat affects all the organisms in it'],
    common_misconceptions: ['Animals can easily move to new habitats', 'Deserts have no life', 'Only big animals matter in an ecosystem'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },

  // Physics (6 topics)
  {
    title: 'Gravity',
    domain: 'science',
    description: 'The invisible force that pulls everything toward the ground and keeps planets in orbit.',
    key_concepts: ['Gravity pulls objects toward Earth', 'Heavier and lighter objects fall at the same speed (without air)', 'Gravity keeps the Moon orbiting Earth', 'Weight depends on gravity'],
    common_misconceptions: ['Heavier objects fall faster', 'There is no gravity in space', 'Gravity only pulls things down'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 11,
  },
  {
    title: 'How Light Works',
    domain: 'science',
    description: 'How light travels, bounces off things, and lets us see colors.',
    key_concepts: ['Light travels in straight lines', 'Light bounces off objects (reflection)', 'White light contains all colors', 'We see objects because light reflects into our eyes'],
    common_misconceptions: ['Our eyes shoot out light to see things', 'Light and dark are opposites that cancel out', 'Mirrors create their own light'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },
  {
    title: 'Sound and Vibrations',
    domain: 'science',
    description: 'How sound is made by vibrations that travel through air to our ears.',
    key_concepts: ['Sound is caused by vibrations', 'Sound travels through air, water, and solids', 'Higher vibrations make higher pitched sounds', 'Sound cannot travel through empty space'],
    common_misconceptions: ['Sound can travel through space', 'Louder sounds travel faster', 'Only musical instruments make vibrations'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 11,
  },
  {
    title: 'Magnets and Magnetism',
    domain: 'science',
    description: 'How magnets attract and repel, and why some materials are magnetic.',
    key_concepts: ['Magnets have north and south poles', 'Opposite poles attract, same poles repel', 'Only some metals are magnetic (iron, nickel, cobalt)', 'Earth itself is a giant magnet'],
    common_misconceptions: ['All metals are magnetic', 'Bigger magnets are always stronger', 'Magnets work on everything'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 10,
  },
  {
    title: 'Electricity Basics',
    domain: 'science',
    description: 'How electricity flows through circuits to power the things we use every day.',
    key_concepts: ['Electricity flows through conductors', 'A circuit needs a complete loop', 'Switches break or complete the circuit', 'Insulators block electricity flow'],
    common_misconceptions: ['Electricity is used up by devices', 'Batteries store electricity', 'Thicker wires always carry more electricity'],
    difficulty_level: 2,
    age_range_min: 8,
    age_range_max: 12,
  },
  {
    title: 'Forces and Motion',
    domain: 'science',
    description: 'How pushes and pulls make things move, speed up, slow down, or change direction.',
    key_concepts: ['A force is a push or pull', 'Friction slows things down', 'Objects stay still or keep moving unless a force acts on them', 'Balanced forces mean no change in motion'],
    common_misconceptions: ['Objects need a constant force to keep moving', 'Heavier objects are harder to stop only because of gravity', 'Friction is always bad'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },

  // Earth Science (5 topics)
  {
    title: 'The Water Cycle',
    domain: 'science',
    description: 'How water moves between the sky, land, and oceans in an endless cycle.',
    key_concepts: ['Evaporation turns water into vapor', 'Condensation forms clouds', 'Precipitation is rain, snow, or hail', 'Water collects in oceans, rivers, and underground'],
    common_misconceptions: ['Clouds are made of cotton or smoke', 'Rain comes from holes in clouds', 'The water cycle only happens when it rains'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 11,
  },
  {
    title: 'Weather and Climate',
    domain: 'science',
    description: 'What causes different kinds of weather and how climate is different from daily weather.',
    key_concepts: ['Weather changes daily, climate is long-term', 'The sun heats Earth unevenly causing wind', 'Clouds form when warm air rises and cools', 'Temperature, wind, and precipitation describe weather'],
    common_misconceptions: ['Weather and climate are the same thing', 'Cold weather disproves global warming', 'It rains more on weekends'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },
  {
    title: 'Volcanoes',
    domain: 'science',
    description: 'How volcanoes form and why they erupt with hot lava from deep inside the Earth.',
    key_concepts: ['Magma is melted rock underground', 'Lava is magma that reaches the surface', 'Volcanoes form at plate boundaries', 'Eruptions can be explosive or slow-flowing'],
    common_misconceptions: ['Volcanoes are just mountains that catch fire', 'All volcanoes look like cones', 'Lava is the most dangerous part of an eruption'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },
  {
    title: 'Rocks and Minerals',
    domain: 'science',
    description: 'The three types of rocks and how they transform over millions of years.',
    key_concepts: ['Igneous rocks form from cooled magma', 'Sedimentary rocks form in layers', 'Metamorphic rocks change under heat and pressure', 'The rock cycle transforms rocks over time'],
    common_misconceptions: ['Rocks never change', 'All rocks are hard', 'Fossils are only found in one type of rock'],
    difficulty_level: 2,
    age_range_min: 8,
    age_range_max: 12,
  },
  {
    title: 'Earthquakes',
    domain: 'science',
    description: 'Why the ground shakes and how tectonic plates move beneath our feet.',
    key_concepts: ['Earth\'s crust is made of moving plates', 'Earthquakes happen when plates slip', 'Seismographs measure earthquake strength', 'Fault lines are where plates meet'],
    common_misconceptions: ['Earthquakes only happen near volcanoes', 'The ground opens up during earthquakes', 'Animals can predict earthquakes reliably'],
    difficulty_level: 2,
    age_range_min: 8,
    age_range_max: 12,
  },

  // Space (4 topics)
  {
    title: 'Our Solar System',
    domain: 'science',
    description: 'The eight planets that orbit our Sun and what makes each one special.',
    key_concepts: ['There are eight planets orbiting the Sun', 'Inner planets are rocky, outer planets are gas giants', 'Planets orbit the Sun due to gravity', 'Each planet has unique features'],
    common_misconceptions: ['Pluto is still a planet', 'The Sun is on fire', 'Planets are close together in space'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 11,
  },
  {
    title: 'Stars and Constellations',
    domain: 'science',
    description: 'What stars are made of and why we see patterns in the night sky.',
    key_concepts: ['Stars are huge balls of hot gas', 'Stars vary in size, color, and temperature', 'Constellations are patterns humans see in star groups', 'Our Sun is a medium-sized star'],
    common_misconceptions: ['Stars are small and close to Earth', 'All stars are the same', 'Constellations are groups of nearby stars'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },
  {
    title: 'Moon Phases',
    domain: 'science',
    description: 'Why the Moon seems to change shape throughout the month.',
    key_concepts: ['The Moon reflects sunlight', 'Moon phases are caused by its position relative to Earth and Sun', 'A full cycle takes about 29 days', 'The Moon doesn\'t actually change shape'],
    common_misconceptions: ['The Moon produces its own light', 'Earth\'s shadow causes moon phases', 'The Moon is only visible at night'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },
  {
    title: 'Day and Night',
    domain: 'science',
    description: 'Why we have daytime and nighttime as the Earth spins on its axis.',
    key_concepts: ['Earth rotates on its axis once every 24 hours', 'The side facing the Sun has daytime', 'The side facing away has nighttime', 'Earth\'s tilt also causes seasons'],
    common_misconceptions: ['The Sun moves around the Earth', 'Night happens because the Sun turns off', 'All places have the same length day'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 10,
  },

  // Chemistry Basics (3 topics)
  {
    title: 'States of Matter',
    domain: 'science',
    description: 'How matter exists as solids, liquids, and gases, and can change between them.',
    key_concepts: ['Solids hold their shape', 'Liquids take the shape of their container', 'Gases spread out to fill any space', 'Heating and cooling change states of matter'],
    common_misconceptions: ['All liquids are like water', 'Gas means the same as gasoline', 'Things disappear when they evaporate'],
    difficulty_level: 1,
    age_range_min: 6,
    age_range_max: 10,
  },
  {
    title: 'Mixtures and Solutions',
    domain: 'science',
    description: 'How different substances combine and how we can separate them again.',
    key_concepts: ['Mixtures contain two or more substances', 'Solutions are mixtures where one substance dissolves in another', 'Mixtures can be separated by filtering, evaporating, or sorting', 'Dissolving is not the same as disappearing'],
    common_misconceptions: ['Sugar disappears when it dissolves', 'All mixtures look mixed up', 'You can\'t separate a mixture once it\'s combined'],
    difficulty_level: 2,
    age_range_min: 7,
    age_range_max: 12,
  },
  {
    title: 'Atoms and Molecules',
    domain: 'science',
    description: 'The tiny building blocks that make up everything around us.',
    key_concepts: ['Everything is made of atoms', 'Atoms are incredibly tiny', 'Molecules are groups of atoms bonded together', 'Different elements have different types of atoms'],
    common_misconceptions: ['Atoms can be seen with a regular microscope', 'Atoms look like tiny solar systems', 'Splitting an atom always causes an explosion'],
    difficulty_level: 3,
    age_range_min: 9,
    age_range_max: 12,
  },
];

export const TEST_PARENT_ID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';
export const TEST_STUDENT_ID = 'b2c3d4e5-f6a7-8901-bcde-f12345678901';
